# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
INHERIT: mkdocs/base.yml  # use the shared AutoRA configuration by default

site_name: AutoRA BMS Theorist
repo_url: 'https://github.com/autoresearch/autora-theorist-bms'

nav:
- Introduction: 'index.md'
- How it works: 'how_it_works.md'
- Meta parameters: 'meta_parameters.md'
- Search space: 'search_space.ipynb'
- Quickstart: 'quick-start.md'
- Examples:
    - Basic usage: 'basic-usage.ipynb'
    - Weber-Fechner Law: 'weber-fechner-example.ipynb'